name: deepl

packages:
  - packages/**

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: melos exec -- dart analyze
    description: Run `dart analyze` for all packages.  

  format:
    run: melos exec -- dart format --fix .
    description: Run `dart format --fix` for all packages.

  format:check:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Run `dart format --set-exit-if-changed` for all packages.

  test:
    run: melos exec -- flutter test --no-pub --test-randomize-ordering-seed random
    description: Run tests for all packages.