name: deepl
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5

dev_dependencies:
  build_runner:
  test: ^1.16.0
  very_good_analysis: ^2.4.0
