name: deepl
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner:
  json_serializable: ^5.0.2
  test: ^1.16.0
  very_good_analysis: ^2.4.0
